name: Build Book

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: make install-deps-ubuntu

      - name: Check Dependencies
        run: make check-deps

      - name: Build PDF
        run: make pdf

      - name: Build PDF with Cover
        run: make pdf-with-cover

      - name: Build ePUB
        run: make epub

      - name: Build ePUB with Cover
        run: make epub-with-cover

      - name: Build HTML
        run: make html

      - name: Build Kindle/MOBI
        run: make kindle

      - name: Upload PDF Asset
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./book/main.pdf
          asset_name: The-Tao-of-Ansible.pdf
          asset_content_type: application/pdf

      - name: Upload PDF with Cover Asset
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./book/The-Tao-of-Ansible-with-cover.pdf
          asset_name: The-Tao-of-Ansible-with-cover.pdf
          asset_content_type: application/pdf

      - name: Upload ePUB Asset
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./book/The-Tao-of-Ansible.epub
          asset_name: The-Tao-of-Ansible.epub
          asset_content_type: application/epub+zip

      - name: Upload ePUB with Cover Asset
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./book/The-Tao-of-Ansible-with-cover.epub
          asset_name: The-Tao-of-Ansible-with-cover.epub
          asset_content_type: application/epub+zip

      - name: Upload MOBI Asset
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./book/The-Tao-of-Ansible.mobi
          asset_name: The-Tao-of-Ansible.mobi
          asset_content_type: application/x-mobipocket-ebook

      - name: Archive HTML Build
        if: github.event_name == 'release'
        run: |
          cd book
          zip -r ../The-Tao-of-Ansible-html.zip *.html *.css

      - name: Upload HTML Archive
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./The-Tao-of-Ansible-html.zip
          asset_name: The-Tao-of-Ansible-html.zip
          asset_content_type: application/zip
